# Lab 1: Basic Python
## Physics 325
### Spring 2016
This lab will follow sections of Chapter 1 in __Computational Physics With Python__ by *Eric Ayars*
The goals are to practice the following python fundamentals:
 * Input
 * Print formatting
 * Array slicing
 * Control structures
     * For
     * While
     * If/else
 * Functions

Input options. Often programs can benefit from live user input. This is less useful in the notebook but it still works in a clever way:

In [ ]:
name = input("My name is: ")

Now we can print the value of the variable `name`. Notice that in comparison to the book, we have to use parenthesis in the `print` statement. In Python3, `print` is a function and therefore takes arguments betwee `(` and `)`.

In [1]:
print(name)

NameError: name 'name' is not defined

**1) Write a single cell that asks for a numeric value and then prints that value multiplied by 10 in a statement that says "Your value times ten is equal to <>" where <> is replaced with the proper value**

In [11]:
# Solution
value = input("Enter a number: ")
print("Your value times ten is equal to:",float(value)*10)

Enter a number: 5
Your value times ten is equal to: 50.0


There are many ways to use python to format printed strings. Unfortunately, the formatting examples on page 18 use an older-style string formatter that is not as automatic. Here is a quick overview of the newer style for python3:

Write the string you want to display in quotes, and put a pair of curly braces `{}` wherever you want to have a variable appear. Then add the format method `.format()` with one argument per variable that needs to go in your string. That's it!

In [122]:
"{} is Pi".format(3.14159)

'3.14159 is Pi'

You can also specify rounding, format as a percentage, pick a different order, or select items from a list or array. For even more examples, <a href="https://docs.python.org/3.1/library/string.html">read the docs</a>.

In [123]:
"{:.6} is Pi rounded to 5 places".format(3.14159265358979323)

'3.14159 is Pi rounded to 5 places'

In [134]:
"{:.1%} is Pi rounded to 5 places".format(23/100)

'23.0% is Pi rounded to 5 places'

In [135]:
"{2} is third, {1} is middle, {0} is first".format(1,2,3)

'3 is third, 2 is middle, 1 is first'

In [136]:
list = ['a','b']
"{0[0]} is the first item, and {0[1]} is the second item".format(list)

'a is the first item, and b is the second item'

Using this knowledge, calculate the area of a circle with radius 23 cm. Print the area in square meters to 5 decimal places.

In [137]:
# Solution
"{:.6}".format(3.14159*0.23**2)

'0.16619'

## Sequence types
1. Write an example of each of the following sequence types: string, tuple, list, dictionary, array. In each case, select one element from the sequence in the appropriate way.
2. How is the tuple different from the others?

In [34]:
# Solution
from numpy import array
mystring = "12345"
print(mystring[3])

mytuple = (1,2,3,4,5)
print(mytuple[3])

mylist = [1,2,3,4,5]
print(mylist[3])

mydict = {1:5,2:3,5:3,7:5,3:4}
print(mydict[3])

myarray = array([1,2,3,4,5])
print(myarray[3])

# Tuple is immutable

4
4
4
4
4


## Array slicing
We will use arrays as one of the primary data types in this course. It is specifically built for numeric data and makes many mathematical operations very fast.

In [45]:
bigarray = array([[1,2,3,4,5,6,7,8,9],[2,4,6,8,10,12,14,16,18],[3,6,9,12,15,18,21,24,27]])
bigarray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [47]:
# select all rows in the column 4:
bigarray[:,4]

array([ 5, 10, 15])

In [48]:
# select row 2:
bigarray[2,:]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [51]:
# select columns 4 through 6:
bigarray[:,4:6]

array([[ 5,  6],
       [10, 12],
       [15, 18]])

Why only two columns, aren't 4 through 6 three values: 4,5,6? It turns out "slicing" is like cutting with a knife, so the slice cuts _between_ the actual data in the array. The figure below helps illustrate this:
<img src="http://www.bogotobogo.com/python/images/python_strings/string_diagram.png">
The figure also shows how negative slices work: they count backwards from the end of the array.

In [64]:
bigarray[:,-1]

array([ 9, 18, 27])

In [61]:
bigarray[:,-3:-1]

array([[ 7,  8],
       [14, 16],
       [21, 24]])

Notice that a slice that uses a range of negative values, still goes from right to left (largest negative first).

In [65]:
bigarray[:,-1:-3]

array([], shape=(3, 0), dtype=int64)

Otherwise it returns an empty array.

The last tidbit of slicing is skip-slicing or strided-slicing. You can add a _third_ element after a second colon to specify the stride of the slice (i.e. how many slices to skip):

In [68]:
bigarray[:,0:4:2]

array([[1, 3],
       [2, 6],
       [3, 9]])

The first two numbers can be left out if you just want to get every other (or every nth) item:

In [69]:
bigarray[:,::2]

array([[ 1,  3,  5,  7,  9],
       [ 2,  6, 10, 14, 18],
       [ 3,  9, 15, 21, 27]])

In [70]:
bigarray[:,::3]

array([[ 1,  4,  7],
       [ 2,  8, 14],
       [ 3, 12, 21]])

These are all really useful when you need them, but it doesn't turn out to be needed often.

## Control structures

Controlling the flow of a program is arguably the most important aspect of computer programming, and what makes programs so good at solving repetative problems. If you face a problem where the solution involves doing the same operation many times or on many objects, then a computer program is a great way to solve your problem. Python has three major control structures: _If_, _While_, and _For_.

These are discussed in the book starting on Page 29.

To understand _If_, you need to practice the conditionals and comparisons on Page 29. After running this first example, create four more comparisons that evaluate to True, and four that evaluate to False. Try to use different types of comparisons, and different object types (string, float, int, complex).

In [85]:
5 > 2

True

Use the syntax in example 1.6.1 to write two more _if_ statements using comparisons:

In [88]:
from numpy import pi
value = 3.14159
if value > pi:
    print("bigger")

bigger


There is a handy kind of _if_ that lets you test items in a list:

In [94]:
name = 'Terry'
cast = ('John', 'Eric', 'Terry', 'Graham', 'Terry', 'Michael')
if name in cast:
    print("yes,", name, "is here")

yes, Terry is here


Use the _if_, _elif_, _else_ structure shown on Page 31 to write a cell that asks for a number and then prints one of the following statements if it is true: "your number is even", "your number is odd" or "your number is even and is 42". Hints: you will have to change the type of the input after it's entered. And, the order of your tests matters.

In [105]:
# Solution
entry = input("Enter your number: ")
number = float(entry)
if number == 42:
    print("your number is 42")
elif (number % 2) == 0:
    print("your number is even")
else:
    print("your number is odd")

Enter your number: 4
your number is even


The _while_ loop is occasionally useful, but can be hard to get right. These rules will help, courtesy of <a href="http://learnpythonthehardway.org/book/ex33.html">Learn Python the Hard Way</a>:
1. Make sure that you use while-loops sparingly. Usually a for-loop is better.
2. Review your while statements and make sure that the boolean test will become False at some point.
3. When in doubt, print out your test variable at the top and bottom of the while-loop to see what it's doing.

An example of this last trick is shown here in a simple while loop that adds a value to a list each time through. Notice the `.append` method that adds items to the list.

In [113]:
i = 0
numbers = []

while i < 6:
    print("At the top i is {}".format(i))
    numbers.append(i)

    i = i + 1
    print("Numbers now: ", numbers)
    print("At the bottom i is {}".format(i))


print("The numbers after loop: ",numbers)

At the top i is 0
Numbers now:  [0]
At the bottom i is 1
At the top i is 1
Numbers now:  [0, 1]
At the bottom i is 2
At the top i is 2
Numbers now:  [0, 1, 2]
At the bottom i is 3
At the top i is 3
Numbers now:  [0, 1, 2, 3]
At the bottom i is 4
At the top i is 4
Numbers now:  [0, 1, 2, 3, 4]
At the bottom i is 5
At the top i is 5
Numbers now:  [0, 1, 2, 3, 4, 5]
At the bottom i is 6
The numbers after loop:  [0, 1, 2, 3, 4, 5]


### The all-powerful _for_ loop